// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2MwvaWk3T-JaksNzZjdMEElywOngV09A',
    appId: '1:826258509624:web:a8763d1e3f97b050c13bcd',
    messagingSenderId: '826258509624',
    projectId: 'who-logbook',
    authDomain: 'who-logbook.firebaseapp.com',
    storageBucket: 'who-logbook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-9sWqHbDeg9hLB_tFByaw53yohaJ1eA',
    appId: '1:826258509624:android:a70abf17783760e2c13bcd',
    messagingSenderId: '826258509624',
    projectId: 'who-logbook',
    storageBucket: 'who-logbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSN8JxudMU7ChJBM21kFqxdvyPZftP0Y',
    appId: '1:826258509624:ios:f8142eee560e2b2cc13bcd',
    messagingSenderId: '826258509624',
    projectId: 'who-logbook',
    storageBucket: 'who-logbook.firebasestorage.app',
    iosClientId: '826258509624-147grv37bepu0f210qmh2759dm4943so.apps.googleusercontent.com',
    iosBundleId: 'com.onelinesolutionltd.whoLogbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABSN8JxudMU7ChJBM21kFqxdvyPZftP0Y',
    appId: '1:826258509624:ios:f8142eee560e2b2cc13bcd',
    messagingSenderId: '826258509624',
    projectId: 'who-logbook',
    storageBucket: 'who-logbook.firebasestorage.app',
    iosClientId: '826258509624-147grv37bepu0f210qmh2759dm4943so.apps.googleusercontent.com',
    iosBundleId: 'com.onelinesolutionltd.whoLogbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2MwvaWk3T-JaksNzZjdMEElywOngV09A',
    appId: '1:826258509624:web:b9ddb69a8c37be89c13bcd',
    messagingSenderId: '826258509624',
    projectId: 'who-logbook',
    authDomain: 'who-logbook.firebaseapp.com',
    storageBucket: 'who-logbook.firebasestorage.app',
  );
}
